/*
  # Add 'proforma' to invoices.status check constraint

  ## Problem
  The mobile app creates invoices with status='proforma' for quote/estimates,
  but the CHECK constraint on invoices.status only allows:
    'pending' | 'paid' | 'overdue' | 'void'

  This causes the error:
    "new row for relation invoices violates check constraint invoices status check"

  ## Solution
  Drop the old constraint and recreate it with 'proforma' included.

  ## Rollback
  ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_status_check;
  ALTER TABLE invoices ADD CONSTRAINT invoices_status_check
    CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'overdue'::text, 'void'::text]));
*/

-- Drop the old constraint (name is auto-generated by Postgres)
ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_status_check;

-- Recreate with proforma included
ALTER TABLE invoices ADD CONSTRAINT invoices_status_check
  CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'overdue'::text, 'void'::text, 'proforma'::text]));

COMMENT ON CONSTRAINT invoices_status_check ON invoices IS
  'Allowed statuses: pending, paid, overdue, void, proforma';
